from import_modules import *


def createModel(dims):
	complete_model = Sequential(name="complete_model")
	complete_model.add(Input(shape=dims))
	complete_model.add(Conv2D(32, (3, 3), padding="same", strides=2))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(64, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(64, (3, 3), padding="same", strides=2))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(128, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(128, (3, 3), padding="same", strides=2))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(256, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(256, (3, 3), padding="same", strides=2))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(15, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(5, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2DTranspose(128, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(UpSampling2D((2, 2)))
	complete_model.add(Conv2DTranspose(64, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2DTranspose(64, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(UpSampling2D((2, 2)))
	complete_model.add(Conv2DTranspose(32, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(Conv2D(3, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(UpSampling2D((2, 2)))
	complete_model.add(Conv2DTranspose(3, (3, 3), padding="same"))
	complete_model.add(PReLU())
	complete_model.add(UpSampling2D((2, 2)))
	complete_model.add(Conv2DTranspose(3, (3, 3), activation="tanh", padding="same"))

	return complete_model